name: Android CI
on:
  push: { branches: [ main ] }
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: 17 }
      - uses: gradle/actions/setup-gradle@v3
        with: { gradle-version: 8.7 }
      - name: Build Debug APK
        run: gradle :app:assembleDebug --no-daemon --stacktrace --info
      - uses: actions/upload-artifact@v4
        with: { name: ASPocket-debug-apk, path: app/build/outputs/apk/debug/*.apk }
